version: "3.3"
services:
  kibana:
    image: docker.io/kibana:7.5.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - /data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  cerebro:
    image: lmenezes/cerebro:latest
    container_name: cerebro
    ports:
      - 9004:9000
    command:
      - "-Dhosts.0.host=http://elastichsearch.douyacun.com:9200"
      - "-Dhosts.1.host=http://116.196.69.34:9200"