version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      # 随机密码，会输出在stdout中
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    user: 1000:50
    volumes:
      - ${DB_PATH_HOST}: /var/lib/mysql