version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      # 随机密码，会输出在stdout中
      MYSQL_RANDOM_ROOT_PASSWORD: pwgen
    ports:
      - "3306:3306"
    user: 1000:50
    volumes:
      - /data/mysql:/var/lib/mysql