version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      # 随机密码，会输出在stdout中
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    user: 1000:50
    volumes:
      - "/data/mysql/data:/var/lib/mysql"
      - "/data/conf.d:/etc/mysql/conf.d"
      - "/data/my.cnf:/etc/my.cnf"