version: "3"
services:
  tea:
    image: registry.cn-hangzhou.aliyuncs.com/douyacun/tea:latest
    container_name: tea
    restart: always
    environment:
      _TEA_CONF: /data/web/tea/configs/prod.ini
    ports:
      - "9003:9003"
    volumes:
      - /data:/data